import GRDB

struct Tag: Codable, Identifiable, Hashable, Sendable {
    var id: Int64?
    /// Primary/German label; also the case-insensitive dedup key.
    var name: String
    var nameEn: String?
}

extension Tag: FetchableRecord, MutablePersistableRecord {
    static let databaseTableName = "tag"

    mutating func didInsert(_ inserted: InsertionSuccess) {
        id = inserted.rowID
    }
}

struct ArticleTag: Codable, Hashable, Sendable {
    var articleId: Int64
    var tagId: Int64
}

extension ArticleTag: FetchableRecord, PersistableRecord {
    static let databaseTableName = "articleTag"
}

/// A tag as generated by the LLM in both languages.
struct GeneratedTag: Sendable {
    var de: String
    var en: String

    /// The sole tag an advertorial gets — the model's own tags are dropped.
    /// Deliberately not an `L10nKey`: tags live bilingually in the DB, so
    /// this one goes through the same dedup path as every generated tag.
    static let advertising = GeneratedTag(de: "Werbung", en: "Advertising")
}

/// A tag prepared for display; the UI picks the label per current language.
/// Tags are stored bilingually (de/en) — every non-German UI language shows
/// the English label.
struct LocalizedTag: Equatable, Hashable, Sendable {
    var name: String
    var nameEn: String?

    func display(_ language: AppLanguage) -> String {
        language == .de ? name : (nameEn.flatMap { $0.isEmpty ? nil : $0 } ?? name)
    }
}
