extension L10nKey {
    static let german: [L10nKey: String] = [
        .welcomeTitle: "Willkommen bei AetherFeed",
        .welcomeSubtitle: "Füge Feeds hinzu, um loszulegen.",

        .settingsGeneral: "Allgemein",
        .settingsOllama: "Ollama",
        .settingsSectionAppearance: "Darstellung & Sprache",
        .settingsSectionFeeds: "Feeds",
        .settingsSectionNotifications: "Benachrichtigungen",
        .settingsSectionUpdates: "Updates",
        .appearance: "Erscheinungsbild",
        .appearanceSystem: "System",
        .appearanceLight: "Hell",
        .appearanceDark: "Dunkel",
        .uiLanguage: "Sprache der Oberfläche",
        .summaryLanguage: "Sprache der Zusammenfassungen",
        .languageGerman: "Deutsch",
        .languageEnglish: "Englisch",
        .languageItalian: "Italienisch",
        .languageFrench: "Französisch",
        .languageSpanish: "Spanisch",
        .summaryLanguageOriginal: "Originalsprache des Artikels",
        .refreshInterval: "Feeds aktualisieren",
        .refreshOff: "Manuell",
        .refreshOnLaunch: "Beim Start",
        .refreshEveryMinutes: "Alle %d Minuten",

        .ollamaSectionConnection: "Verbindung",
        .ollamaHost: "Hostname",
        .ollamaPort: "Port",
        .ollamaModel: "Modell",

        .sidebarAll: "Alle Artikel",
        .sidebarUnread: "Ungelesen",
        .sidebarCategories: "Kategorien",
        .sidebarNoCategory: "Ohne Kategorie",
        .addFeed: "Feed hinzufügen",
        .addFeedURL: "Feed-URL",
        .addFeedCategory: "Kategorie",
        .addFeedNoCategory: "Keine",
        .addFeedNewCategory: "Neue Kategorie",
        .addFeedAdd: "Hinzufügen",
        .cancel: "Abbrechen",
        .deleteFeed: "Feed löschen",
        .refresh: "Aktualisieren",
        .openInBrowser: "Im Browser öffnen",
        .noArticleSelected: "Kein Artikel ausgewählt",
        .emptyListTitle: "Keine Artikel",
        .untitledArticle: "Ohne Titel",
        .errorInvalidURL: "Ungültige Feed-URL",
        .errorHTTP: "Server antwortete mit Status %d",
        .errorNotAFeed: "Unter dieser Adresse wurde kein RSS/Atom-Feed gefunden",

        .sidebarTags: "Tags",
        .settingsOllamaTest: "Verbindung testen",
        .settingsOllamaTestSuccess: "✓ %d Modelle gefunden",
        .aiSummary: "KI-Zusammenfassung",
        .aiProcessing: "Wird zusammengefasst …",
        .aiPaused: "KI-Verarbeitung pausiert",
        .retry: "Erneut versuchen",
        .errorLLMNotConfigured: "KI ist nicht konfiguriert — in den Einstellungen einrichten",
        .errorLLMNoModel: "Kein Modell ausgewählt",
        .errorLLMUnreachable: "KI-Server nicht erreichbar: %@",
        .errorLLMUnauthorized: "Ungültiger oder fehlender API-Schlüssel",
        .errorLLMBadResponse: "Unerwartete Antwort vom KI-Server",

        .settingsAI: "KI",
        .llmProvider: "Anbieter",
        .providerOllama: "Ollama",
        .providerOpenAI: "OpenAI / kompatibel",
        .openaiBaseURL: "Basis-URL",
        .openaiAPIKey: "API-Schlüssel",

        .sidebarHome: "Startseite",
        .digestTitle: "Das ist neu",
        .digestUpdated: "Aktualisiert",
        .digestEmpty: "Noch kein Überblick",
        .digestEmptyHint: "Der Überblick wird erstellt, sobald die KI konfiguriert ist und ungelesene Artikel vorliegen.",
        .digestEmptyCreating: "Noch keine Zusammenfassung verfügbar — sie wird gerade erstellt, sobald alle Artikel von der KI verarbeitet wurden.",
        .addFeedSuggest: "Kategorie vorschlagen",

        .searchPrompt: "Suchen",
        .opmlImport: "OPML importieren …",
        .opmlExport: "OPML exportieren …",
        .settingsCategories: "Kategorien",
        .settingsCategoriesEmpty: "Noch keine Kategorien",
        .settingsCategoryDelete: "Kategorie löschen (Feeds bleiben erhalten)",

        .markAllRead: "Alle als gelesen markieren",
        .settingsRetention: "Gelesene Artikel aufbewahren",
        .retentionUnlimited: "Unbegrenzt",
        .retentionDaysFormat: "%d Tage",
        .settingsNotifications: "Bei neuen Artikeln benachrichtigen",
        .notifyNewArticlesBody: "%d neue Artikel",

        .digestGenerating: "Wird erstellt — kann hinter laufenden Zusammenfassungen warten …",
        .digestNoArticles: "Keine Artikel vorhanden — erst Feeds hinzufügen oder aktualisieren",
        .uiLanguageRestartHint: "Systemmenüs (Ablage, Bearbeiten …) übernehmen die Sprache nach einem Neustart der App.",
        .digestOverviewTitle: "Die letzten 24 Stunden",
        .digestOverviewEmpty: "Keine neuen Artikel in den letzten 24 Stunden.",
        .detailShowWebPage: "Webseite anzeigen",
        .detailShowFeedText: "Feed-Text anzeigen",
        .shareLink: "Link teilen",
        .pendingSummariesHelp: "%d Artikel warten auf die KI-Zusammenfassung",
        .settingsCategoryColor: "Farbe der Kategorie",
        .settingsCategoryColorClear: "Farbe entfernen",
        .settingsCategoryReorderHint: "Zum Sortieren ziehen",

        .settingsAdBlock: "Ad-Blocker",
        .adBlockEnable: "Ad-Blocker aktivieren",
        .adBlockLists: "Blocklisten",
        .adBlockNoLists: "Noch keine Blocklisten. Füge eine URL im Adblock-Format hinzu.",
        .adBlockAddPlaceholder: "Blocklisten-URL",
        .adBlockUpdateNow: "Jetzt aktualisieren",
        .adBlockUpdating: "Lädt und kompiliert …",
        .adBlockActiveRules: "%d Regeln aktiv",
        .adBlockHint: "Nur Netzwerk-Blocking (Werbe-/Tracker-Domains) in der Artikel-Webansicht. Listen im Adblock-Format, z. B. hagezi. Große Listen brauchen beim ersten Aktualisieren etwas Zeit.",
        .adBlockTurnOn: "Ad-Blocker einschalten",
        .adBlockTurnOff: "Ad-Blocker ausschalten",

        .providerApple: "Apple Intelligence (lokal)",
        .appleModelName: "Systemmodell (lokal)",
        .appleStatus: "Status",
        .settingsAppleTestSuccess: "✓ Apple Intelligence ist verfügbar",
        .errorAppleNotSupported: "Dieser Mac unterstützt Apple Intelligence nicht",
        .errorAppleNotEnabled:
            "Apple Intelligence ist deaktiviert — bitte in den Systemeinstellungen aktivieren",
        .errorAppleModelNotReady:
            "Das Apple-Intelligence-Modell ist noch nicht bereit (wird geladen) — später erneut versuchen",
        .errorAppleOSTooOld: "Apple Intelligence erfordert macOS 26 oder neuer",
        .errorAppleUnavailable: "Apple Intelligence ist derzeit nicht verfügbar",
        .errorAppleRejected: "Apple Intelligence hat die Verarbeitung dieses Inhalts abgelehnt",

        .digestReadAloud: "Vorlesen",
        .digestStopReading: "Vorlesen stoppen",

        .settingsNotifySummaries: "Benachrichtigen, wenn der Digest bereitsteht",
        .notifyDigestReadyBody: "Dein Digest ist bereit",
        .settingsCheckUpdates: "Beim Start auf Updates prüfen",
        .updateAvailableHelp: "Version %@ verfügbar – klicken zum Aktualisieren",

        .aiFailedTitle: "KI-Zusammenfassung fehlgeschlagen",
        .aiFailedUnknown: "Unbekannter Fehler",
        .feedErrorHelp: "Letzter Abruf fehlgeschlagen: %@",
        .markRead: "Als gelesen markieren",
        .markUnread: "Als ungelesen markieren",
        .copyLink: "Link kopieren",
        .renameFeed: "Feed umbenennen …",
        .renameFeedSave: "Sichern",
        .moveToCategory: "In Kategorie verschieben",
        .sidebarStarred: "Markiert",
        .star: "Markieren",
        .unstar: "Markierung entfernen",
        .exportMenu: "Exportieren",
        .exportMarkdown: "Als Markdown …",
        .exportPDF: "Als PDF …",
    ]
}
