extension L10nKey {
    static let english: [L10nKey: String] = [
        .welcomeTitle: "Welcome to AetherFeed",
        .welcomeSubtitle: "Add feeds to get started.",

        .settingsGeneral: "General",
        .settingsOllama: "Ollama",
        .uiLanguage: "Interface language",
        .summaryLanguage: "Summary language",
        .languageGerman: "German",
        .languageEnglish: "English",
        .languageItalian: "Italian",
        .languageFrench: "French",
        .languageSpanish: "Spanish",
        .summaryLanguageOriginal: "Article's original language",
        .refreshInterval: "Refresh feeds",
        .refreshOff: "Manually",
        .refreshOnLaunch: "On launch",
        .refreshEveryMinutes: "Every %d minutes",

        .ollamaSectionConnection: "Connection",
        .ollamaHost: "Hostname",
        .ollamaPort: "Port",
        .ollamaModel: "Model",

        .sidebarAll: "All articles",
        .sidebarUnread: "Unread",
        .sidebarCategories: "Categories",
        .sidebarNoCategory: "No category",
        .addFeed: "Add feed",
        .addFeedURL: "Feed URL",
        .addFeedCategory: "Category",
        .addFeedNoCategory: "None",
        .addFeedNewCategory: "New category",
        .addFeedAdd: "Add",
        .cancel: "Cancel",
        .deleteFeed: "Delete feed",
        .refresh: "Refresh",
        .openInBrowser: "Open in browser",
        .noArticleSelected: "No article selected",
        .emptyListTitle: "No articles",
        .untitledArticle: "Untitled",
        .errorInvalidURL: "Invalid feed URL",
        .errorHTTP: "Server responded with status %d",
        .errorNotAFeed: "No RSS/Atom feed found at this address",

        .sidebarTags: "Tags",
        .settingsOllamaTest: "Test connection",
        .settingsOllamaTestSuccess: "✓ %d models found",
        .aiSummary: "AI summary",
        .aiProcessing: "Summarizing …",
        .aiPaused: "AI processing paused",
        .retry: "Retry",
        .errorLLMNotConfigured: "AI is not configured — set it up in Settings",
        .errorLLMNoModel: "No model selected",
        .errorLLMUnreachable: "AI server unreachable: %@",
        .errorLLMUnauthorized: "Invalid or missing API key",
        .errorLLMBadResponse: "Unexpected response from the AI server",

        .settingsAI: "AI",
        .llmProvider: "Provider",
        .providerOllama: "Ollama",
        .providerOpenAI: "OpenAI / compatible",
        .openaiBaseURL: "Base URL",
        .openaiAPIKey: "API key",

        .sidebarHome: "Home",
        .digestTitle: "What's new",
        .digestUpdated: "Updated",
        .digestEmpty: "No briefing yet",
        .digestEmptyHint: "The briefing is generated once AI is configured and there are unread articles.",
        .digestEmptyCreating: "No briefing available yet — it is created once the AI has processed all articles.",
        .addFeedSuggest: "Suggest category",

        .searchPrompt: "Search",
        .opmlImport: "Import OPML …",
        .opmlExport: "Export OPML …",
        .settingsCategories: "Categories",
        .settingsCategoriesEmpty: "No categories yet",
        .settingsCategoryDelete: "Delete category (feeds are kept)",

        .markAllRead: "Mark all as read",
        .settingsRetention: "Keep read articles",
        .retentionUnlimited: "Unlimited",
        .retentionDaysFormat: "%d days",
        .settingsNotifications: "Notify about new articles",
        .notifyNewArticlesBody: "%d new articles",

        .digestGenerating: "Generating — may wait behind running summaries …",
        .digestNoArticles: "No articles available — add or refresh feeds first",
        .uiLanguageRestartHint: "System menus (File, Edit …) adopt the language after restarting the app.",
        .digestOverviewTitle: "The last 24 hours",
        .digestOverviewEmpty: "No new articles in the last 24 hours.",
        .detailShowWebPage: "Show web page",
        .detailShowFeedText: "Show feed text",
        .shareLink: "Share link",
        .pendingSummariesHelp: "%d articles waiting for AI summary",
        .settingsCategoryColor: "Category color",
        .settingsCategoryColorClear: "Remove color",

        .settingsAdBlock: "Ad blocker",
        .adBlockEnable: "Enable ad blocker",
        .adBlockLists: "Blocklists",
        .adBlockNoLists: "No blocklists yet. Add a URL in Adblock format.",
        .adBlockAddPlaceholder: "Blocklist URL",
        .adBlockUpdateNow: "Update now",
        .adBlockUpdating: "Downloading and compiling …",
        .adBlockActiveRules: "%d rules active",
        .adBlockHint: "Network blocking only (ad/tracker domains) in the article web view. Adblock-format lists, e.g. hagezi. Large lists take a moment on first update.",
        .adBlockTurnOn: "Turn ad blocker on",
        .adBlockTurnOff: "Turn ad blocker off",

        .providerApple: "Apple Intelligence (on-device)",
        .appleModelName: "System model (on-device)",
        .appleStatus: "Status",
        .settingsAppleTestSuccess: "✓ Apple Intelligence is available",
        .errorAppleNotSupported: "This Mac does not support Apple Intelligence",
        .errorAppleNotEnabled: "Apple Intelligence is turned off — enable it in System Settings",
        .errorAppleModelNotReady:
            "The Apple Intelligence model is not ready yet (downloading) — try again later",
        .errorAppleOSTooOld: "Apple Intelligence requires macOS 26 or later",
        .errorAppleUnavailable: "Apple Intelligence is currently unavailable",
        .errorAppleRejected: "Apple Intelligence declined to process this content",

        .digestReadAloud: "Read aloud",
        .digestStopReading: "Stop reading",

        .settingsNotifySummaries: "Notify when the digest is ready",
        .notifyDigestReadyBody: "Your digest is ready",
        .settingsCheckUpdates: "Check for updates at launch",
        .updateAvailableHelp: "Version %@ available – click to update",

        .aiFailedTitle: "AI summary failed",
        .aiFailedUnknown: "Unknown error",
        .feedErrorHelp: "Last refresh failed: %@",
        .markRead: "Mark as read",
        .markUnread: "Mark as unread",
        .copyLink: "Copy link",
        .renameFeed: "Rename feed …",
        .renameFeedSave: "Save",
        .moveToCategory: "Move to category",
        .sidebarStarred: "Starred",
        .star: "Star",
        .unstar: "Unstar",
        .exportMenu: "Export",
        .exportMarkdown: "As Markdown …",
        .exportPDF: "As PDF …",
    ]
}
