extension L10nKey {
    static let french: [L10nKey: String] = [
        .welcomeTitle: "Bienvenue dans AetherFeed",
        .welcomeSubtitle: "Ajoutez des flux pour commencer.",

        .settingsGeneral: "Général",
        .settingsOllama: "Ollama",
        .settingsSectionAppearance: "Apparence et langue",
        .settingsSectionFeeds: "Flux",
        .settingsSectionNotifications: "Notifications",
        .settingsSectionUpdates: "Mises à jour",
        .appearance: "Apparence",
        .appearanceSystem: "Système",
        .appearanceLight: "Clair",
        .appearanceDark: "Sombre",
        .uiLanguage: "Langue de l'interface",
        .summaryLanguage: "Langue des résumés",
        .languageGerman: "Allemand",
        .languageEnglish: "Anglais",
        .languageItalian: "Italien",
        .languageFrench: "Français",
        .languageSpanish: "Espagnol",
        .summaryLanguageOriginal: "Langue originale de l'article",
        .refreshInterval: "Actualiser les flux",
        .refreshOff: "Manuellement",
        .refreshOnLaunch: "Au démarrage",
        .refreshEveryMinutes: "Toutes les %d minutes",

        .ollamaSectionConnection: "Connexion",
        .ollamaHost: "Nom d'hôte",
        .ollamaPort: "Port",
        .ollamaModel: "Modèle",

        .sidebarAll: "Tous les articles",
        .sidebarUnread: "Non lus",
        .sidebarCategories: "Catégories",
        .sidebarNoCategory: "Sans catégorie",
        .addFeed: "Ajouter un flux",
        .addFeedURL: "URL du flux",
        .addFeedCategory: "Catégorie",
        .addFeedNoCategory: "Aucune",
        .addFeedNewCategory: "Nouvelle catégorie",
        .addFeedAdd: "Ajouter",
        .cancel: "Annuler",
        .deleteFeed: "Supprimer le flux",
        .refresh: "Actualiser",
        .openInBrowser: "Ouvrir dans le navigateur",
        .noArticleSelected: "Aucun article sélectionné",
        .emptyListTitle: "Aucun article",
        .untitledArticle: "Sans titre",
        .errorInvalidURL: "URL de flux invalide",
        .errorHTTP: "Le serveur a répondu avec le statut %d",
        .errorNotAFeed: "Aucun flux RSS/Atom trouvé à cette adresse",

        .sidebarTags: "Tags",
        .settingsOllamaTest: "Tester la connexion",
        .settingsOllamaTestSuccess: "✓ %d modèles trouvés",
        .aiSummary: "Résumé IA",
        .aiProcessing: "Résumé en cours …",
        .aiPaused: "Traitement IA en pause",
        .aiPausedOnBattery: "Sur batterie – reprise sur secteur",
        .retry: "Réessayer",
        .errorLLMNotConfigured: "L'IA n'est pas configurée — configurez-la dans les Réglages",
        .errorLLMNoModel: "Aucun modèle sélectionné",
        .errorLLMUnreachable: "Serveur IA inaccessible : %@",
        .errorLLMUnauthorized: "Clé API invalide ou manquante",
        .errorLLMBadResponse: "Réponse inattendue du serveur IA",
        .errorInsecureEndpoint:
            "La clé API serait transmise en clair — utilisez https:// (ou un serveur du réseau local)",
        .ollamaHostHint: "Sans schéma : http sur le réseau local, https sinon",

        .settingsAI: "IA",
        .llmProvider: "Fournisseur",
        .providerOllama: "Ollama",
        .providerOpenAI: "OpenAI / compatible",
        .openaiBaseURL: "URL de base",
        .openaiAPIKey: "Clé API",
        .settingsPauseOnBattery: "Suspendre le traitement IA sur batterie",
        .settingsPauseOnBatteryHint:
            "Apple Intelligence s'exécute localement sur ce Mac. Sur batterie, la file "
            + "d'attente et le briefing restent en pause et reprennent automatiquement une "
            + "fois l'appareil branché.",

        .sidebarHome: "Accueil",
        .digestTitle: "Quoi de neuf",
        .digestUpdated: "Mis à jour",
        .digestEmpty: "Pas encore de synthèse",
        .digestEmptyHint:
            "La synthèse est générée dès que l'IA est configurée et qu'il y a des articles non lus.",
        .digestEmptyCreating:
            "Aucune synthèse disponible — elle sera créée une fois que l'IA aura traité tous les articles.",
        .addFeedSuggest: "Suggérer une catégorie",

        .searchPrompt: "Rechercher",
        .opmlImport: "Importer OPML …",
        .opmlExport: "Exporter OPML …",
        .settingsCategories: "Catégories",
        .settingsCategoriesEmpty: "Pas encore de catégorie",
        .settingsCategoryDelete: "Supprimer la catégorie (les flux sont conservés)",

        .markAllRead: "Tout marquer comme lu",
        .settingsRetention: "Conserver les articles lus",
        .retentionUnlimited: "Illimité",
        .retentionDaysFormat: "%d jours",
        .settingsNotifications: "Notifier les nouveaux articles",
        .notifyNewArticlesBody: "%d nouveaux articles",

        .digestGenerating: "Génération en cours — peut attendre la fin des résumés …",
        .digestNoArticles: "Aucun article disponible — ajoutez ou actualisez d'abord des flux",
        .uiLanguageRestartHint:
            "Les menus système (Fichier, Édition …) adoptent la langue au redémarrage de l'app.",
        .digestOverviewTitle: "Les dernières 24 heures",
        .digestOverviewEmpty: "Aucun nouvel article dans les dernières 24 heures.",
        .detailShowWebPage: "Afficher la page web",
        .detailShowFeedText: "Afficher le texte du flux",
        .shareLink: "Partager le lien",
        .pendingSummariesHelp: "%d articles en attente du résumé IA",
        .settingsCategoryColor: "Couleur de la catégorie",
        .settingsCategoryColorClear: "Retirer la couleur",
        .settingsCategoryReorderHint: "Faites glisser pour réordonner",

        .settingsAdBlock: "Bloqueur de publicités",
        .adBlockEnable: "Activer le bloqueur de publicités",
        .adBlockLists: "Listes de blocage",
        .adBlockNoLists: "Pas encore de liste. Ajoutez une URL au format Adblock.",
        .adBlockAddPlaceholder: "URL de la liste de blocage",
        .adBlockUpdateNow: "Mettre à jour maintenant",
        .adBlockUpdating: "Téléchargement et compilation …",
        .adBlockActiveRules: "%d règles actives",
        .adBlockHint:
            "Blocage réseau uniquement (domaines publicitaires/traqueurs) dans la vue web de l'article. Listes au format Adblock, p. ex. hagezi. Les grandes listes prennent un moment à la première mise à jour.",
        .adBlockTurnOn: "Activer le bloqueur de publicités",
        .adBlockTurnOff: "Désactiver le bloqueur de publicités",

        .providerApple: "Apple Intelligence (sur l'appareil)",
        .appleModelName: "Modèle système (sur l'appareil)",
        .appleStatus: "État",
        .settingsAppleTestSuccess: "✓ Apple Intelligence est disponible",
        .errorAppleNotSupported: "Ce Mac ne prend pas en charge Apple Intelligence",
        .errorAppleNotEnabled:
            "Apple Intelligence est désactivée — activez-la dans Réglages Système",
        .errorAppleModelNotReady:
            "Le modèle Apple Intelligence n'est pas encore prêt (téléchargement) — réessayez plus tard",
        .errorAppleOSTooOld: "Apple Intelligence nécessite macOS 26 ou ultérieur",
        .errorAppleUnavailable: "Apple Intelligence est actuellement indisponible",
        .errorAppleRejected: "Apple Intelligence a refusé de traiter ce contenu",

        .digestReadAloud: "Lire à voix haute",
        .digestStopReading: "Arrêter la lecture",

        .settingsNotifySummaries: "Notifier quand la synthèse est prête",
        .notifyDigestReadyBody: "Votre synthèse est prête",
        .settingsCheckUpdates: "Rechercher des mises à jour au démarrage",
        .updateAvailableHelp: "Version %@ disponible – cliquez pour mettre à jour",

        .aiFailedTitle: "Échec du résumé IA",
        .aiFailedUnknown: "Erreur inconnue",
        .feedErrorHelp: "Dernière actualisation échouée : %@",
        .markRead: "Marquer comme lu",
        .markUnread: "Marquer comme non lu",
        .copyLink: "Copier le lien",
        .renameFeed: "Renommer le flux …",
        .renameFeedSave: "Enregistrer",
        .moveToCategory: "Déplacer vers la catégorie",
        .sidebarStarred: "Favoris",
        .star: "Ajouter aux favoris",
        .unstar: "Retirer des favoris",
        .exportMenu: "Exporter",
        .exportMarkdown: "En Markdown …",
        .exportPDF: "En PDF …",
    ]
}
