extension L10nKey {
    static let italian: [L10nKey: String] = [
        .welcomeTitle: "Benvenuto in AetherFeed",
        .welcomeSubtitle: "Aggiungi dei feed per iniziare.",

        .settingsGeneral: "Generale",
        .settingsOllama: "Ollama",
        .settingsSectionAppearance: "Aspetto e lingua",
        .settingsSectionFeeds: "Feed",
        .settingsSectionNotifications: "Notifiche",
        .settingsSectionUpdates: "Aggiornamenti",
        .appearance: "Aspetto",
        .appearanceSystem: "Sistema",
        .appearanceLight: "Chiaro",
        .appearanceDark: "Scuro",
        .uiLanguage: "Lingua dell'interfaccia",
        .summaryLanguage: "Lingua dei riassunti",
        .languageGerman: "Tedesco",
        .languageEnglish: "Inglese",
        .languageItalian: "Italiano",
        .languageFrench: "Francese",
        .languageSpanish: "Spagnolo",
        .summaryLanguageOriginal: "Lingua originale dell'articolo",
        .refreshInterval: "Aggiorna feed",
        .refreshOff: "Manualmente",
        .refreshOnLaunch: "All'avvio",
        .refreshEveryMinutes: "Ogni %d minuti",

        .ollamaSectionConnection: "Connessione",
        .ollamaHost: "Nome host",
        .ollamaPort: "Porta",
        .ollamaModel: "Modello",

        .sidebarAll: "Tutti gli articoli",
        .sidebarUnread: "Non letti",
        .sidebarCategories: "Categorie",
        .sidebarNoCategory: "Senza categoria",
        .addFeed: "Aggiungi feed",
        .addFeedURL: "URL del feed",
        .addFeedCategory: "Categoria",
        .addFeedNoCategory: "Nessuna",
        .addFeedNewCategory: "Nuova categoria",
        .addFeedAdd: "Aggiungi",
        .cancel: "Annulla",
        .deleteFeed: "Elimina feed",
        .refresh: "Aggiorna",
        .openInBrowser: "Apri nel browser",
        .noArticleSelected: "Nessun articolo selezionato",
        .emptyListTitle: "Nessun articolo",
        .untitledArticle: "Senza titolo",
        .errorInvalidURL: "URL del feed non valido",
        .errorHTTP: "Il server ha risposto con stato %d",
        .errorNotAFeed: "Nessun feed RSS/Atom trovato a questo indirizzo",

        .sidebarTags: "Tag",
        .settingsOllamaTest: "Prova connessione",
        .settingsOllamaTestSuccess: "✓ %d modelli trovati",
        .aiSummary: "Riassunto AI",
        .aiProcessing: "Riassumendo …",
        .aiPaused: "Elaborazione AI in pausa",
        .retry: "Riprova",
        .errorLLMNotConfigured: "L'AI non è configurata — impostala nelle Impostazioni",
        .errorLLMNoModel: "Nessun modello selezionato",
        .errorLLMUnreachable: "Server AI non raggiungibile: %@",
        .errorLLMUnauthorized: "Chiave API non valida o mancante",
        .errorLLMBadResponse: "Risposta inattesa dal server AI",

        .settingsAI: "AI",
        .llmProvider: "Provider",
        .providerOllama: "Ollama",
        .providerOpenAI: "OpenAI / compatibile",
        .openaiBaseURL: "URL di base",
        .openaiAPIKey: "Chiave API",

        .sidebarHome: "Inizio",
        .digestTitle: "Novità",
        .digestUpdated: "Aggiornato",
        .digestEmpty: "Ancora nessun riepilogo",
        .digestEmptyHint:
            "Il riepilogo viene generato quando l'AI è configurata e ci sono articoli non letti.",
        .digestEmptyCreating:
            "Nessun riepilogo disponibile — verrà creato quando l'AI avrà elaborato tutti gli articoli.",
        .addFeedSuggest: "Suggerisci categoria",

        .searchPrompt: "Cerca",
        .opmlImport: "Importa OPML …",
        .opmlExport: "Esporta OPML …",
        .settingsCategories: "Categorie",
        .settingsCategoriesEmpty: "Ancora nessuna categoria",
        .settingsCategoryDelete: "Elimina categoria (i feed vengono mantenuti)",

        .markAllRead: "Segna tutti come letti",
        .settingsRetention: "Conserva articoli letti",
        .retentionUnlimited: "Illimitato",
        .retentionDaysFormat: "%d giorni",
        .settingsNotifications: "Notifica nuovi articoli",
        .notifyNewArticlesBody: "%d nuovi articoli",

        .digestGenerating: "Generazione in corso — potrebbe attendere i riassunti in corso …",
        .digestNoArticles: "Nessun articolo disponibile — aggiungi o aggiorna prima i feed",
        .uiLanguageRestartHint:
            "I menu di sistema (Archivio, Modifica …) adottano la lingua al riavvio dell'app.",
        .digestOverviewTitle: "Le ultime 24 ore",
        .digestOverviewEmpty: "Nessun nuovo articolo nelle ultime 24 ore.",
        .detailShowWebPage: "Mostra pagina web",
        .detailShowFeedText: "Mostra testo del feed",
        .shareLink: "Condividi link",
        .pendingSummariesHelp: "%d articoli in attesa del riassunto AI",
        .settingsCategoryColor: "Colore della categoria",
        .settingsCategoryColorClear: "Rimuovi colore",

        .settingsAdBlock: "Blocco pubblicità",
        .adBlockEnable: "Attiva blocco pubblicità",
        .adBlockLists: "Liste di blocco",
        .adBlockNoLists: "Ancora nessuna lista. Aggiungi un URL in formato Adblock.",
        .adBlockAddPlaceholder: "URL della lista di blocco",
        .adBlockUpdateNow: "Aggiorna ora",
        .adBlockUpdating: "Download e compilazione …",
        .adBlockActiveRules: "%d regole attive",
        .adBlockHint:
            "Solo blocco di rete (domini pubblicitari/tracker) nella vista web dell'articolo. Liste in formato Adblock, ad es. hagezi. Le liste grandi richiedono un momento al primo aggiornamento.",
        .adBlockTurnOn: "Attiva blocco pubblicità",
        .adBlockTurnOff: "Disattiva blocco pubblicità",

        .providerApple: "Apple Intelligence (sul dispositivo)",
        .appleModelName: "Modello di sistema (sul dispositivo)",
        .appleStatus: "Stato",
        .settingsAppleTestSuccess: "✓ Apple Intelligence è disponibile",
        .errorAppleNotSupported: "Questo Mac non supporta Apple Intelligence",
        .errorAppleNotEnabled:
            "Apple Intelligence è disattivata — attivala nelle Impostazioni di Sistema",
        .errorAppleModelNotReady:
            "Il modello Apple Intelligence non è ancora pronto (download in corso) — riprova più tardi",
        .errorAppleOSTooOld: "Apple Intelligence richiede macOS 26 o successivo",
        .errorAppleUnavailable: "Apple Intelligence non è al momento disponibile",
        .errorAppleRejected: "Apple Intelligence ha rifiutato di elaborare questo contenuto",

        .digestReadAloud: "Leggi ad alta voce",
        .digestStopReading: "Interrompi lettura",

        .settingsNotifySummaries: "Notifica quando il riepilogo è pronto",
        .notifyDigestReadyBody: "Il tuo riepilogo è pronto",
        .settingsCheckUpdates: "Cerca aggiornamenti all'avvio",
        .updateAvailableHelp: "Versione %@ disponibile – fai clic per aggiornare",

        .aiFailedTitle: "Riassunto AI non riuscito",
        .aiFailedUnknown: "Errore sconosciuto",
        .feedErrorHelp: "Ultimo aggiornamento non riuscito: %@",
        .markRead: "Segna come letto",
        .markUnread: "Segna come non letto",
        .copyLink: "Copia link",
        .renameFeed: "Rinomina feed …",
        .renameFeedSave: "Salva",
        .moveToCategory: "Sposta nella categoria",
        .sidebarStarred: "Preferiti",
        .star: "Aggiungi ai preferiti",
        .unstar: "Rimuovi dai preferiti",
        .exportMenu: "Esporta",
        .exportMarkdown: "Come Markdown …",
        .exportPDF: "Come PDF …",
    ]
}
