extension L10nKey {
    static let spanish: [L10nKey: String] = [
        .welcomeTitle: "Bienvenido a AetherFeed",
        .welcomeSubtitle: "Añade feeds para empezar.",

        .settingsGeneral: "General",
        .settingsOllama: "Ollama",
        .settingsSectionAppearance: "Apariencia e idioma",
        .settingsSectionFeeds: "Feeds",
        .settingsSectionNotifications: "Notificaciones",
        .settingsSectionUpdates: "Actualizaciones",
        .appearance: "Apariencia",
        .appearanceSystem: "Sistema",
        .appearanceLight: "Claro",
        .appearanceDark: "Oscuro",
        .uiLanguage: "Idioma de la interfaz",
        .summaryLanguage: "Idioma de los resúmenes",
        .languageGerman: "Alemán",
        .languageEnglish: "Inglés",
        .languageItalian: "Italiano",
        .languageFrench: "Francés",
        .languageSpanish: "Español",
        .summaryLanguageOriginal: "Idioma original del artículo",
        .refreshInterval: "Actualizar feeds",
        .refreshOff: "Manualmente",
        .refreshOnLaunch: "Al iniciar",
        .refreshEveryMinutes: "Cada %d minutos",

        .ollamaSectionConnection: "Conexión",
        .ollamaHost: "Nombre de host",
        .ollamaPort: "Puerto",
        .ollamaModel: "Modelo",

        .sidebarAll: "Todos los artículos",
        .sidebarUnread: "No leídos",
        .sidebarCategories: "Categorías",
        .sidebarNoCategory: "Sin categoría",
        .addFeed: "Añadir feed",
        .addFeedURL: "URL del feed",
        .addFeedCategory: "Categoría",
        .addFeedNoCategory: "Ninguna",
        .addFeedNewCategory: "Nueva categoría",
        .addFeedAdd: "Añadir",
        .cancel: "Cancelar",
        .deleteFeed: "Eliminar feed",
        .refresh: "Actualizar",
        .openInBrowser: "Abrir en el navegador",
        .noArticleSelected: "Ningún artículo seleccionado",
        .emptyListTitle: "Sin artículos",
        .untitledArticle: "Sin título",
        .errorInvalidURL: "URL de feed no válida",
        .errorHTTP: "El servidor respondió con estado %d",
        .errorNotAFeed: "No se encontró ningún feed RSS/Atom en esta dirección",

        .sidebarTags: "Etiquetas",
        .settingsOllamaTest: "Probar conexión",
        .settingsOllamaTestSuccess: "✓ %d modelos encontrados",
        .aiSummary: "Resumen de IA",
        .aiProcessing: "Resumiendo …",
        .aiPaused: "Procesamiento de IA en pausa",
        .retry: "Reintentar",
        .errorLLMNotConfigured: "La IA no está configurada — configúrala en Ajustes",
        .errorLLMNoModel: "Ningún modelo seleccionado",
        .errorLLMUnreachable: "Servidor de IA inaccesible: %@",
        .errorLLMUnauthorized: "Clave API no válida o ausente",
        .errorLLMBadResponse: "Respuesta inesperada del servidor de IA",

        .settingsAI: "IA",
        .llmProvider: "Proveedor",
        .providerOllama: "Ollama",
        .providerOpenAI: "OpenAI / compatible",
        .openaiBaseURL: "URL base",
        .openaiAPIKey: "Clave API",

        .sidebarHome: "Inicio",
        .digestTitle: "Novedades",
        .digestUpdated: "Actualizado",
        .digestEmpty: "Aún no hay resumen diario",
        .digestEmptyHint:
            "El resumen diario se genera cuando la IA está configurada y hay artículos sin leer.",
        .digestEmptyCreating:
            "Aún no hay resumen diario — se creará cuando la IA haya procesado todos los artículos.",
        .addFeedSuggest: "Sugerir categoría",

        .searchPrompt: "Buscar",
        .opmlImport: "Importar OPML …",
        .opmlExport: "Exportar OPML …",
        .settingsCategories: "Categorías",
        .settingsCategoriesEmpty: "Aún no hay categorías",
        .settingsCategoryDelete: "Eliminar categoría (los feeds se conservan)",

        .markAllRead: "Marcar todo como leído",
        .settingsRetention: "Conservar artículos leídos",
        .retentionUnlimited: "Sin límite",
        .retentionDaysFormat: "%d días",
        .settingsNotifications: "Notificar artículos nuevos",
        .notifyNewArticlesBody: "%d artículos nuevos",

        .digestGenerating: "Generando — puede esperar a que terminen los resúmenes en curso …",
        .digestNoArticles: "No hay artículos disponibles — añade o actualiza feeds primero",
        .uiLanguageRestartHint:
            "Los menús del sistema (Archivo, Edición …) adoptan el idioma al reiniciar la app.",
        .digestOverviewTitle: "Las últimas 24 horas",
        .digestOverviewEmpty: "Ningún artículo nuevo en las últimas 24 horas.",
        .detailShowWebPage: "Mostrar página web",
        .detailShowFeedText: "Mostrar texto del feed",
        .shareLink: "Compartir enlace",
        .pendingSummariesHelp: "%d artículos esperando el resumen de IA",
        .settingsCategoryColor: "Color de la categoría",
        .settingsCategoryColorClear: "Quitar color",

        .settingsAdBlock: "Bloqueador de anuncios",
        .adBlockEnable: "Activar bloqueador de anuncios",
        .adBlockLists: "Listas de bloqueo",
        .adBlockNoLists: "Aún no hay listas. Añade una URL en formato Adblock.",
        .adBlockAddPlaceholder: "URL de la lista de bloqueo",
        .adBlockUpdateNow: "Actualizar ahora",
        .adBlockUpdating: "Descargando y compilando …",
        .adBlockActiveRules: "%d reglas activas",
        .adBlockHint:
            "Solo bloqueo de red (dominios de anuncios/rastreadores) en la vista web del artículo. Listas en formato Adblock, p. ej. hagezi. Las listas grandes tardan un momento en la primera actualización.",
        .adBlockTurnOn: "Activar bloqueador de anuncios",
        .adBlockTurnOff: "Desactivar bloqueador de anuncios",

        .providerApple: "Apple Intelligence (en el dispositivo)",
        .appleModelName: "Modelo del sistema (en el dispositivo)",
        .appleStatus: "Estado",
        .settingsAppleTestSuccess: "✓ Apple Intelligence está disponible",
        .errorAppleNotSupported: "Este Mac no es compatible con Apple Intelligence",
        .errorAppleNotEnabled:
            "Apple Intelligence está desactivada — actívala en Ajustes del Sistema",
        .errorAppleModelNotReady:
            "El modelo de Apple Intelligence aún no está listo (descargando) — inténtalo más tarde",
        .errorAppleOSTooOld: "Apple Intelligence requiere macOS 26 o posterior",
        .errorAppleUnavailable: "Apple Intelligence no está disponible en este momento",
        .errorAppleRejected: "Apple Intelligence rechazó procesar este contenido",

        .digestReadAloud: "Leer en voz alta",
        .digestStopReading: "Detener lectura",

        .settingsNotifySummaries: "Notificar cuando el resumen diario esté listo",
        .notifyDigestReadyBody: "Tu resumen diario está listo",
        .settingsCheckUpdates: "Buscar actualizaciones al iniciar",
        .updateAvailableHelp: "Versión %@ disponible – haz clic para actualizar",

        .aiFailedTitle: "Falló el resumen de IA",
        .aiFailedUnknown: "Error desconocido",
        .feedErrorHelp: "La última actualización falló: %@",
        .markRead: "Marcar como leído",
        .markUnread: "Marcar como no leído",
        .copyLink: "Copiar enlace",
        .renameFeed: "Renombrar feed …",
        .renameFeedSave: "Guardar",
        .moveToCategory: "Mover a la categoría",
        .sidebarStarred: "Destacados",
        .star: "Destacar",
        .unstar: "Quitar de destacados",
        .exportMenu: "Exportar",
        .exportMarkdown: "Como Markdown …",
        .exportPDF: "Como PDF …",
    ]
}
